[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
regex = "1.11.1"
reqwest = { version = "0.12.24", features = ["blocking", "cookies"] }
rstest = "0.23.0"
