[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cached = "0.56.0"
itertools = "0.14.0"
microlp = "0.2.11"
regex = "1.11.1"
reqwest = { version = "0.12.24", features = ["blocking", "cookies"] }
rstest = "0.23.0"
